version: '2'

services:
  app:
    image: 'assessment:latest'
    build:
      context: .
    container_name: assessment
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sailings
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    ports:
      - 8080:8080

  db:
    image: 'postgres:15'
    container_name: db
    environment:
      - POSTGRES_DB=sailings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    expose:
      - 5432
    ports:
      - 5432:5432
